name: travel_bucket_list
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.0.15
  build_runner: ^2.4.15
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  http: ^1.3.0
  permission_handler: ^11.4.0
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
